### ISSUE TITLE
[Anon] Bug report: Wood Elves - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/blood-bowl-2016#1]
**File:** Wood Elves - BB16.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** In  BB 2020 rules war dancers from wood elf roster cost 125 000 and no more 120 000

**Comment by shaner11** [comment]
This data is meant for legacy players who wish to use the rules from the 2016 edition of Blood Bowl. The main Blood Bowl catalogue has been updated in line with the new edition, and you should switch to it if you wish to make teams using the new rules.
